version: '3.6'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    environment:
      - elasticsearch.url=http://localhost:9200
    ports:
      - "5601:5601"
    networks:
      - esnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet

networks:
  esnet:
    driver: bridge
